# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8086579d513b2c2223b67cd63747219c43837a83c4d9c5d91d8426f68e245c1e24796a794da31f3d88be91f5411aa93efb35ce60cb6139ad7679fc90c2e1db07

test:
  secret_key_base: 8048578826fa417a03df314ce63dfc759bd5ca60c9c1090e1e0b772ed6eba0696db0725efc43366eb70c23eb135e9a90492bd00357714446e522914afd328a82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
